@startuml container-diagram-generale
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define SPRITESURL https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.0/sprites
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME_5 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome

!include FONTAWESOME_5/mobile_alt.puml
!include FONTAWESOME_5/globe.puml
!include FONTAWESOME_5/database.puml
!include FONTAWESOME_5/server.puml
!include FONTAWESOME_5/envelope.puml
!include FONTAWESOME_5/aws.puml
!include SPRITESURL/rabbitmq.puml

!include FONTAWESOME/gear.puml


Person(customer, "Utente", "Utente piattaforma")

System_Boundary(c1, "Piattaforma") {
    Container(spa, "Single-Page App", "Web browser", "Client per gestire le funzionalià del sistema attraverso browser","globe")
    Container(backend_api, "API Web", "Node.js", "Eroga servizi attraverso una interfaccia REST", "server")
    Container(rabbit, "Message Broker","RabbitMQ","","rabbitmq")
    Container(mailer, "Microservizio Mailer","Node.js", "Template e invio di email","gear")
    ContainerDb(mongo, "Database", "NoSQL Database", "Salve le informazioni degli utenti, di autenticazione, ...", "database")
}

System_Ext(ses, "Email System", "Amazon Simple Email Service","aws")

Rel(customer, spa, "Usa", "HTTPS")

Rel(spa, backend_api, "Usa", "HTTPS")
Rel_Back_Neighbor(mongo,backend_api, "Legge e scrive su")
Rel_D(backend_api, rabbit,"Invia messaggi", "AMQP")
Rel_L(mailer, rabbit,"Recupera messaggi", "AMQP")
Rel_U(mailer, ses, "Richiede invio email", "HTTPS")
Rel_U(ses,customer, "Invia email verso", "SMTP")


hide stereotype
legend right
|<color:$LEGEND_TITLE_COLOR>**Legend**</color> |
|<$PERSON_BG_COLOR> person |
|<$CONTAINER_BG_COLOR> container |
|<$EXTERNAL_SYSTEM_BG_COLOR> external system |
endlegend


@enduml